webtalk_init -webtalk_dir C:\\Users\\jialf\\Desktop\\work\\fpgaModule\\pl_rest\\pl_rest\\pl_rest.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2023-01-10 11:32:57" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bpsmnjps31lbf6svqlg95gkeab" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_15" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.130 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1673315902144" -context "sdk\\\\hardware/1673315902144"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1673315902144"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1673315902144"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1673315902144"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3" -context "sdk\\\\hardware/1673315902144"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1673315902144"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1673315902144"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1673315902144"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1673315902144"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1673315902144"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1673315902144"
webtalk_add_data -client sdk -key uid -value "1673315961519" -context "sdk\\\\bsp/1673315961519"
webtalk_add_data -client sdk -key hwid -value "1673315902144" -context "sdk\\\\bsp/1673315961519"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1673315961519"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1673315961519"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1673315961519"
webtalk_add_data -client sdk -key uid -value "1673315965664" -context "sdk\\\\application/1673315965664"
webtalk_add_data -client sdk -key hwid -value "1673315902144" -context "sdk\\\\application/1673315965664"
webtalk_add_data -client sdk -key bspid -value "1673315961519" -context "sdk\\\\application/1673315965664"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1673315965664"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1673315965664"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1673315965664"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1673315965664"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1673315965664"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1673315965664"
webtalk_add_data -client sdk -key projSize -value "238.22265625" -context "sdk\\\\application/1673315965664"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1673321577970"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1673321577970"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1673321577970"
webtalk_add_data -client sdk -key DebugCount -value "10" -context "sdk\\\\bsp/1673321577970"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1673321577970"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1673321577970"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1673321577970"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1673321577970"
webtalk_transmit -clientid 4137023698 -regid "" -xml C:\\Users\\jialf\\Desktop\\work\\fpgaModule\\pl_rest\\pl_rest\\pl_rest.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\jialf\\Desktop\\work\\fpgaModule\\pl_rest\\pl_rest\\pl_rest.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\jialf\\Desktop\\work\\fpgaModule\\pl_rest\\pl_rest\\pl_rest.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
